//! Analysis/Rules Engine Layer
//!
//! Processes vision results and applies game-specific rules to generate tips and alerts.
//! Uses rhai scripting for customizable game profiles.

pub mod rules;
pub mod events;

use anyhow::Result;
use crate::vision::VisionResult;

/// A tip or alert generated by the analysis engine
#[derive(Debug, Clone)]
pub struct Tip {
    /// Tip identifier
    pub id: String,
    /// Display message
    pub message: String,
    /// Priority level (higher = more important)
    pub priority: u32,
    /// Duration to display in milliseconds (None = until dismissed)
    pub duration_ms: Option<u64>,
    /// Whether to play audio notification
    pub play_sound: bool,
}

/// Analysis engine that processes vision results
pub struct AnalysisEngine {
    // TODO: Loaded game profile
    // TODO: Rhai scripting engine
}

impl AnalysisEngine {
    /// Create a new analysis engine
    pub fn new() -> Result<Self> {
        Ok(Self {})
    }

    /// Load a game profile
    pub fn load_profile(&mut self, _profile_path: &str) -> Result<()> {
        // TODO: Load and parse game profile
        Ok(())
    }

    /// Analyze vision results and generate tips
    pub fn analyze(&self, _vision_result: &VisionResult) -> Result<Vec<Tip>> {
        // TODO: Run rules against vision data
        Ok(vec![])
    }
}

impl Default for AnalysisEngine {
    fn default() -> Self {
        Self::new().expect("Failed to create analysis engine")
    }
}
